const MILLI = 1000;
const CLOCK = 60;
const DAY_TO_HOUR = 24;
const MOUNTHS_TO_YEAR = 12;
const DAYS_TO_MOUNTH = 30;
const DAYS_TO_WEEK = 7;

export const HOUR_TO_MILLISECONDS = MILLI * CLOCK ** 2;
export const DAY_TO_MILLISECONDS = HOUR_TO_MILLISECONDS * DAY_TO_HOUR;
export const WEEK_TO_MILLISECONDS = DAY_TO_MILLISECONDS * DAYS_TO_WEEK;
export const MOUNTH_TO_MILLISECONDS = DAY_TO_MILLISECONDS * DAYS_TO_MOUNTH;
export const YEAR_TO_MILLISECONDS = MOUNTH_TO_MILLISECONDS * MOUNTHS_TO_YEAR;
